### ISSUE TITLE
Message Error 

### ISSUE THREAD

**Issue by Mohseenhabib** [NagariaHussain/doppio_bot#6]
Invalid file path: doppiobot_ui.bundle.jsx
<img width="1440" alt="Screenshot 2023-04-30 at 1 31 37 PM" src="https://user-images.githubusercontent.com/65990429/235348412-2e13cd87-96f7-4e2c-9b84-e395bde3a7b8.png">

**Comment by NagariaHussain** [comment]
Hi 👋 

What is the Frappe version you are using?

**Comment by Mohseenhabib** [comment]
Frappe Framework: v15.x.x-develop () (develop)

**Comment by NagariaHussain** [comment]
Can you open browser console and share the error traceback?

Also, you can try running 

```
bench build --app doppio_bot 
```

**Comment by Mohseenhabib** [comment]
still the same error

**Comment by Mohseenhabib** [comment]
[Error] Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 56, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 53, in handle
    return _RESTAPIHandler(call, doctype, name).get_response()
  File "apps/frappe/frappe/api.py", line 69, in get_response
    return self.handle_method()
  File "apps/frappe/frappe/api.py", line 79, in handle_method
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 48, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 86, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1589, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 341, in get_js
    frappe.throw(_("Invalid file path: {0}").format("/".join(src)))
  File "apps/frappe/frappe/__init__.py", line 523, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 491, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 440, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Invalid file path: doppiobot_ui.bundle.jsx

	(anonymous function) (desk.bundle.E4KSZO2M.js:31491)
	forEach
	(anonymous function) (desk.bundle.E4KSZO2M.js:31489)
	(anonymous function) (desk.bundle.E4KSZO2M.js:31390)
	fire (libs.bundle.5H56RLYJ.js:1751)
	fireWith (libs.bundle.5H56RLYJ.js:1837)
	done (libs.bundle.5H56RLYJ.js:5307)
	(anonymous function) (libs.bundle.5H56RLYJ.js:5473)

**Comment by NagariaHussain** [comment]
Was the issue resolved? Doesn't look like an issue caused by the app itself. Bench was unable to build the asset properly.

**Comment by Mohseenhabib** [comment]
I tried installing on different bench but i get the same traceback error.

**Comment by NagariaHussain** [comment]
What is your NodeJS version?

**Comment by Mohseenhabib** [comment]
Node.js v19.5.0

**Comment by NagariaHussain** [comment]
Try V16
