### ISSUE TITLE
Current Quota Exceeded Error

### ISSUE THREAD

**Issue by asoral** [NagariaHussain/doppio_bot#7]
**I Get:**
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

**Details of the error:**
### App Versions
```
{
	"chat": "0.0.1",
	"doppio_bot": "0.0.1",
	"erpnext": "14.26.0",
	"frappe": "14.37.0",
	"helpdesk": "0.8.4",
	"hrms": "14.4.0",
	"payments": "0.0.1"
}
```
### Route
```
doppio-bot
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/doppio_bot/doppio_bot/api.py", line 48, in get_chatbot_response
    response = conversation_chain.run(prompt_message)
  File "env/lib/python3.10/site-packages/langchain/chains/base.py", line 213, in run
    return self(args[0])[self.output_keys[0]]
  File "env/lib/python3.10/site-packages/langchain/chains/base.py", line 116, in __call__
    raise e
  File "env/lib/python3.10/site-packages/langchain/chains/base.py", line 113, in __call__
    outputs = self._call(inputs)
  File "env/lib/python3.10/site-packages/langchain/chains/llm.py", line 57, in _call
    return self.apply([inputs])[0]
  File "env/lib/python3.10/site-packages/langchain/chains/llm.py", line 118, in apply
    response = self.generate(input_list)
  File "env/lib/python3.10/site-packages/langchain/chains/llm.py", line 62, in generate
    return self.llm.generate_prompt(prompts, stop)
  File "env/lib/python3.10/site-packages/langchain/llms/base.py", line 107, in generate_prompt
    return self.generate(prompt_strings, stop=stop)
  File "env/lib/python3.10/site-packages/langchain/llms/base.py", line 140, in generate
    raise e
  File "env/lib/python3.10/site-packages/langchain/llms/base.py", line 137, in generate
    output = self._generate(prompts, stop=stop)
  File "env/lib/python3.10/site-packages/langchain/llms/openai.py", line 672, in _generate
    full_response = completion_with_retry(self, messages=messages, **params)
  File "env/lib/python3.10/site-packages/langchain/llms/openai.py", line 99, in completion_with_retry
    return _completion_with_retry(**kwargs)
  File "env/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "env/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "env/lib/python3.10/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "env/lib/python3.10/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "env/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "env/lib/python3.10/site-packages/langchain/llms/openai.py", line 97, in _completion_with_retry
    return llm.client.create(**kwargs)
  File "env/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "env/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "env/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "env/lib/python3.10/site-packages/openai/api_requestor.py", line 620, in _interpret_response
    self._interpret_response_line(
  File "env/lib/python3.10/site-packages/openai/api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"prompt_message": "can you read my data",
		"session_id": "IoayygO4-xhLIAvB8AE2Z"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/doppio_bot.api.get_chatbot_response"
}
```
### Response Data
```
{
	"exception": "openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details."
}
```

**It does show limits on the OpenAI Dashboard through**
![image](https://github.com/NagariaHussain/doppio_bot/assets/11851156/e7e0a8b0-6689-4ad0-b307-444f1f421ae9)

**Comment by NagariaHussain** [comment]
Not an issue with the app, check if your API's usage is what the screenshot shows.

The model used: "gpt-3.5-turbo"
