### ISSUE TITLE
Error loading assets

### ISSUE THREAD

**Issue by itsdipak** [NagariaHussain/doppio_bot#8]
When we open page, showing below error :

request.js:298 TypeError: frappe.assets.handler[frappe.assets.extn(...)] is not a function
    at Object.eval_assets (assets.js:96:50)
    at assets.js:83:19
    at Object.callback (assets.js:134:5)
    at Object.callback [as success_callback] (request.js:85:16)
    at 200 (request.js:128:34)
    at Object.<anonymous> (request.js:294:6)

**Comment by NagariaHussain** [comment]
What is the Frappe version?
